services:
  app:
    container_name: app-reservation
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db-reservation
    image: postgres:16.3-alpine3.19
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data